### ISSUE TITLE
Mapping from cell ontology class number to labels?

### ISSUE THREAD

**Issue by joycekang** [czbiohub/tabula-muris-senis#12]
Hello! Thanks for making this dataset well-organized. I might be missing something obvious, but is there a file that provides a mapping of cell ontology class numbers (int) to the actual name of the cell type ("B cell")? Also, what is the difference between "cell.ontology.class", "cell.ontology.id", and "free.annotation" columns in the @meta.data in droplet_filtered.h5ad? Thanks so much!

**Comment by aopisco** [comment]
hi @joycekang 
the mapping you're missing might have to do with you reading the `h5ad` file in R instead of Python. Have you try using the `loom` file and convert it to RDS first?

**Comment by joycekang** [comment]
Thanks for the response! I was indeed trying to read the `h5ad` file in R. Where is the `loom` file located? I downloaded the processed data from the `tms_gene_data` folder from [https://figshare.com/projects/Tabula_Muris_Senis/64982] but don't see any `loom` files.

**Comment by joycekang** [comment]
Update: I was able to resolve this by reading in the `h5ad` file using scanpy then exporting the `.obs` dataframe as a `.csv` file to read into R. Thanks!
