### ISSUE TITLE
How to access the cell type annotation

### ISSUE THREAD

**Issue by onebeingmay** [czbiohub/tabula-muris-senis#15]
Dear Tabula team,
I downloaded the processed data from https://figshare.com/projects/Tabula_Muris_Senis/64982 and loaded the data into R using Seurat's `ReadH5AD` function. When I checked the meta.data I cannot find the cell type annotation? For example, https://github.com/czbiohub/tabula-muris/blob/master/22_markers/droplet_Lung_cell_ontology_class_classes.csv listed the cell type annotation, but I don't know which column it corresponds to in the meta.data? Here is an example of the meta.data of the lung droplet data set:

age cell cell.ontology.class cell.ontology.id free.annotation method mouse.id nFeatures_RNA sex subtissue tissue tissue.free.annotation nCount_RNA louvain cluster.names leiden
AAACCTGAGCGTAATA-1-11-0-0 2 MACA_18m_F_LUNG_50_AAACCTGAGCGTAATA 0 4 0 0 6 2470 0 2 0 0 6594.1533203125 33 35 35
AAACGGGTCGCCCTTA-1-11-0-0 2 MACA_18m_F_LUNG_50_AAACGGGTCGCCCTTA 0 4 0 0 6 1821 0 2 0 0 5138.74755859375 8 8 8
AAAGATGAGCAGACTG-1-11-0-0 2 MACA_18m_F_LUNG_50_AAAGATGAGCAGACTG 6 7 6 0 6 1333 0 2 0 0 4399.15380859375 5 2 2
AAAGATGAGCCGTCGT-1-11-0-0 2 MACA_18m_F_LUNG_50_AAAGATGAGCCGTCGT 8 8 8 0 6 1455 0 2 0 0 4933.3740234375 4 1 1
AAAGCAACATGGTAGG-1-11-0-0 2 MACA_18m_F_LUNG_50_AAAGCAACATGGTAGG 5 3 5 0 6 3322 0 2 0 0 7091.1279296875 6 3 3
AAATGCCAGGAGTTGC-1-11-0-0 2 MACA_18m_F_LUNG_50_AAATGCCAGGAGTTGC 6 7 6 0 6 1300 0 2 0 0 4612.63916015625 5 2 2

Thank!

**Comment by aopisco** [comment]
@onebeingmay we don't recommend using `ReadH5AD` as other members in the community run into similar issues. I'd suggest for you to first convert the file to `loom` and then use [sceasy](https://cellgeni.readthedocs.io/en/latest/visualisations.html):
```
sceasy:::convertFormat('filename.loom', from="loom", to="anndata",
                       outFile='filename.h5ad')
```

if you would like help creating the loom files please let me know

**Comment by onebeingmay** [comment]
@aopisco Thank you for your quick response! Did you mean if I first convert the downloaded h5ad objects to loom then back to h5ad using ```
sceasy:::convertFormat('filename.loom', from="loom", to="anndata",
                       outFile='filename.h5ad')
```
can load the cell type annotation information correctly? May I know which column of the meta.data is the cell type annotation? The column names I found include:
 [1] "age"                 "cell"                "cell.ontology.class" "cell.ontology.id"    "cellid"             
 [6] "free.annotation"     "method"              "mouse.id"            "plate"               "sex"                
[11] "subtissue"           "tissue"              "well"                "nFeatures_RNA"       "nCount_RNA"         
[16] "louvain"             "cluster.names"       "leiden"              "cluster.number"
Thanks!

**Comment by aopisco** [comment]
@onebeingmay my mistake, I meant first convert to loom then convert to single cell experiment 
```
sceasy:::convertFormat('filename.loom', from="loom", to="sce",
                       outFile='filename.rds')
```
the file you are pointing to is from Tabula Muris and not Tabula Muris Senis.
For that file -- which will not match Tabula Muris Senis -- the cell type annotations are in `cell.ontology.class`

**Comment by onebeingmay** [comment]
@aopisco Thank you! So does the hdad files I downloaded from https://figshare.com/projects/Tabula_Muris_Senis/64982 contain cell type annotation information?

**Comment by aopisco** [comment]
yes, exactly, if you're looking for a single organ I recommend you use the ones split by tissue [here](https://figshare.com/articles/dataset/Tabula_Muris_Senis_Data_Objects/12654728)

**Comment by onebeingmay** [comment]
Thanks @aopisco . I downloaded the tabula-muris-senis-facs-processed-official-annotations-Lung.h5ad from your link and the columns of the metadata include 
 [1] "FACS.selection"      "age"                 "cell"                "cell.ontology.class" "cell.ontology.id"   
 [6] "free.annotation"     "method"              "mouse.id"            "sex"                 "subtissue"          
[11] "tissue"              "nFeatures_RNA"       "nCount_RNA"          "louvain"             "leiden"  
May I know which column is the cell type annotation?

**Comment by aopisco** [comment]
`cell.ontology.class`

**Comment by onebeingmay** [comment]
Thanks! The cell.ontology.class contains 32 categories (number 0-31). Does Tabula Muris Senis provide a mapping from these numbers to actual cell type name (i.e. lung endothelial cell, stromal cell, etc)?

**Comment by aopisco** [comment]
you are getting to this result because you are importing the file to R and that is not compatible. There are cell labels and not numbers -- that lung object match what you can search here: https://tabula-muris-senis.ds.czbiohub.org/lung/facs/

**Comment by onebeingmay** [comment]
Thank you! I load the data using scanpy and now can see the correct labels.

**Comment by aopisco** [comment]
Closing the issue for now as this sounds resolved! Feel free to re-open

**Comment by hanhyebin** [comment]
I want to piggyback on this: what command/package do you recommend using to convert the hdf5 file to loom to then convert to sce? 

Thanks!

**Comment by Nidane** [comment]
may i ask how would u guys suggest to convert the h5ad file into a loom file ? thanks!
