### ISSUE TITLE
Help downloading data in other ways

### ISSUE THREAD

**Issue by ShuilinLiao** [czbiohub/tabula-muris-senis#16]
It's appreciate to be able to download the Tabula Muris Senis data from Amazon. However, registering an AWS account requires binding a credit card. For some reasons, I cannot obtain a valid credit card, which causes me failing register an AWS account. Is it convenient for you to provide other ways to download data? Thank you so much!

**Comment by aopisco** [comment]
@ShuilinLiao the processed data is available from [figshare](https://figshare.com/articles/dataset/Tabula_Muris_Senis_Data_Objects/12654728)

Do you need raw fastq files?

**Comment by ShuilinLiao** [comment]
Thanks for your  prompt and kindly response. I think the processed data is OK. But I have some questions about the structure about the repository, the scirpts directory named 1_tabula_muris_senis 
input data mentioned in the scripts. Can I think the , for example

**Comment by ShuilinLiao** [comment]
Thanks for your prompt and kindly response. I think the processed data is sufficient. 
The published paper studying ageing tissues in mouse through single cell transcriptomic (_nature_ 2020) interested me very much and I think it is useful for me to learn the analyze of single-cell sequencing data.
However, due to my poor understanding, I have some questions about the structure about the git repository. I think the scirpts in the directory "1_tabula_muris_senis" can reduce the figures 1-4 in the published article, but I can not find the input data mentioned in the scripts  from figshare.  
For example, in the script titled with "1_tabula_muris_senis/11_figure_1/tabula-muris-senis-droplet-processing.ipynb", 3 data  "MACA_10x_1_3_30.csv" , "TM_droplet_metadata.csv" and "TM_droplet_mat.h5ad" were coded as input data,  but I can not find them from figshare. Therefore I am wondering whether my understanding is wrong or there are oder bewteen some scripts, which generate the mentioned data.
Would you help me solve the questiones? 
Best wishes for you and looking forward to your kind reply.

**Comment by aopisco** [comment]
@ShuilinLiao can you give me a bit more context on what you’re trying to do?

**Comment by bjstewart1** [comment]
> @ShuilinLiao the processed data is available from [figshare](https://figshare.com/articles/dataset/Tabula_Muris_Senis_Data_Objects/12654728)
> 
> Do you need raw fastq files?

I am looking to download either raw fastq files or the BAM files.
Inputting credit card details for amazon to register for one of these accounts is pretty unpalatable and may not work for some users. Navigating aws is not straightforward.

Is there any way you can make these data available through more classical channels - tabula muris has the raw data on SRA which is easily accessible for example.

**Comment by aopisco** [comment]
Hi Benjamin,

unfortunately the size of the dataset is not manageable through the more
conventional channels.
Let me know if you need help navigating AWS.

Best,
Angela
