### ISSUE TITLE
An expression matrix for the SCAT tissue is required

### ISSUE THREAD

**Issue by Laura-1997** [czbiohub/tabula-muris-senis#17]
I would like the SCAT data you measured for further analysis, preferably its expression matrix.
     I have tried to download it on AWS. The steps are to first enter Plate_seq and then download the data for each month. For the data in 3_month, I selected the path of SCAT organization through fastqs_annotated.csv in 3_month, and downloaded the file with the suffix gencode.vm19.ercc.htseq-count.txt and finally merged it. This method cannot find all the 3_month cells of the SCAT.
    In the folders of 24_month and 18_month, I tried to download the CSV files under each folder and tried to filter the SCAT cells with the csv named annotation information of tabula-Muris-Senis-facs-official-raw-obj_cell-metadata.csv. But they were all fewer than 100 cells selected. 
    This was the only way I could think of to get the SCAT representation matrix for each month, but it didn't work. Could you tell me how I can get it? Or can you send the expression matrix of SCAT to my mailbox?My email is 51191300127@stu.ecnu.edu.cn

**Comment by aopisco** [comment]
Hi @Laura-1997 the data is available from [figshare](https://figshare.com/articles/dataset/Tabula_Muris_Senis_Data_Objects/12654728)

Let me know if that works for you.

**Comment by Laura-1997** [comment]
Thanks for your reply! Do you mean the  document named tabula-muris-senis-facs-processed-official-annotations-SCAT.h5ad?
I used to open it through a Python package called 'Annadata' (anndata.read_h5ad), but failed to get the expression matrix. Can you tell me if I select the right way ? Or which method should I choose?

**Comment by aopisco** [comment]
@Laura-1997 yes exactly, as for the code I'd suggest you to familiarize with Scanpy and perhaps follow this [tutorial](https://github.com/theislab/single-cell-tutorial/blob/master/latest_notebook/Case-study_Mouse-intestinal-epithelium_1906.ipynb)

**Comment by Laura-1997** [comment]
Thanks. I will.
