### ISSUE TITLE
FACS Brain Non-Myeloid 3-month data are NaN and 18, 24 data are Neuronal

### ISSUE THREAD

**Issue by hannalemmik** [czbiohub/tabula-muris-senis#20]
Dear Tabula Muris team,

I am trying to understand an aspect of your aligned raw read dataset from Gene Expression Omnibus. Namely, FACS Brain Non-Myeloid cell age classes seem to be divided as explained and illustrated below.

only Neuronal cells: 
sc.pl.umap(nonan,color=['age','subtissue']) 
#this returns 18 and 24 months data only,  and 2x each subtissue (i.e. 2xcerebellum, 2xcortex, 2xhippocampus, 2xstriatum)
[umapnonan_age_subtissue.pdf](https://github.com/czbiohub/tabula-muris-senis/files/5476227/umapnonan_age_subtissue.pdf)

only NaN cells: 
sc.pl.umap(yesnan,color=['age','subtissue']) 
#this returns 3 months data only, and 1x each subtissue (i.e. 1xcerebellum, 1xcortex, 1xhippocampus, 1xstriatum)
[umapyesnan_age_subtissue.pdf](https://github.com/czbiohub/tabula-muris-senis/files/5476230/umapyesnan_age_subtissue.pdf)

In the Nature paper you say: "Data from the 3-month time point—which has previously been published and constitutes the Tabula Muris5 represents approximately 20% of the cells in the entire dataset, and was used as a basis from which to perform semi-automated cell-type annotation of the data from the additional time points (Fig. 1b, Extended Data Fig. 4b)." 

Does this mean that the 3-month data points come from the original Tabula Muris Consortium, were not analysed with FACS for Tabula Muris Senis, and the GEO files contain combined batch corrected experiments from both Tabula Muris and Tabula Muris Senis?

I hope you can answer my question. 

Sincerely,
Hanna

**Comment by aopisco** [comment]
Hi @hannalemmik, are you able to point me to the files you are using?
You can find the complete Brain Non-myeloid data in [figshare](https://figshare.com/articles/dataset/Tabula_Muris_Senis_Data_Objects/12654728?file=23872787)
