### ISSUE TITLE
About data interpretation

### ISSUE THREAD

**Issue by VP0521** [czbiohub/tabula-muris-senis#22]
Hi,
I want to know how can I understand how the expression of a gene changes with age in a particular tissue from tubula Muris Senis. Is there any information available online which I can refer to understand it. 

I tried selecting the tissue/age/gender/cell type/gene I am interested in. It just seem same to me and not understandable.

thanks!

**Comment by aopisco** [comment]
@VP0521 did you check out online data portal?

https://tabula-muris-senis.ds.czbiohub.org/

feel free to reach out by email if you want to schedule a call

**Comment by VP0521** [comment]
> @VP0521 did you check out online data portal?
> 
> https://tabula-muris-senis.ds.czbiohub.org/
> 
> feel free to reach out by email if you want to schedule a call

Hi, Can I get your email ID to contact you?

**Comment by VP0521** [comment]
> @VP0521 did you check out online data portal?
> 
> https://tabula-muris-senis.ds.czbiohub.org/
> 
> feel free to reach out by email if you want to schedule a call

@aopisco Hi, Can I get your email ID to contact you?

**Comment by VP0521** [comment]
Hi, I just want to learn to use tabula muris senis. I tried it, however,
there are certain aspects which I am not able to understand.
Could you please help me with learning Tabula muris senis?

Thanks and regards
