### ISSUE TITLE
Question about data downloading

### ISSUE THREAD

**Issue by vikki0816** [czbiohub/tabula-muris-senis#25]
Dear Tabula Muris team,

I'm trying to download the raw data from AWS, but I really confused with the file name of the datasets. I want to know the meaning of the subfolder name like "170907_A00111_0051_BH2HWLDMXX". 

Futhermore, I only need raw data from brain cells in my study, but I could not figure out the brain cells. Could you please tell me how to distinguish the brain cells from other tissues according to the filename? 

I really hope you can answer my question. Thanks a lot !

Sincerely,
Vikki

**Comment by aopisco** [comment]
@vikki0816 unfortunately there is not an easy way to do this, my suggestion is for you to use the metadata files (`s3://czb-tabula-muris-senis/Metadata/`) and programmatically find your fastqs of interest
