### ISSUE TITLE
WBC

### ISSUE THREAD

**Issue by anahSG** [czbiohub/tabula-muris-senis#26]
Hi!

When you download the experimental design there is a group named "White_Blood_Cells". I have now try to retrieve the fastq files and I don't see the same annotation. Could you point out which files have the information with the fastq file names and the cell ranger outputs? Or just the WBC fastq files would be sufficient. I can only find the metadata corresponding to fastq files for the Plate_seq data sets, where could I find the same file for the 10x fastq files?

Thank you!

Ana

**Comment by aopisco** [comment]
hi @anahSG we don't have WBC in the dataset
