### ISSUE TITLE
bbknn metadata file

### ISSUE THREAD

**Issue by donshiva88** [czbiohub/tabula-muris-senis#27]
Hi,

thank you for providing all these beautiful single cell data.
I downloaded the "tabula-muris-senis-bbknn-processed-official-annotations.h5ad".
I am more familiar with Seurat, which is why I converted the file with the new
"seurat-disk" tool. Everything works fine, but the annotations are missing.
As far as I learned, this is probably because storage in the $uns part of the *.h5ad files 
is not recognized by Seurat (or the intermediate h5seurat).
However, this issue has been frequently brought up
(https://github.com/czbiohub/tabula-muris-senis/issues/6; https://github.com/satijalab/seurat/issues/1427),
but for now not with the new created bbknn file (https://figshare.com/articles/dataset/Processed_files_to_use_with_scanpy_/8273102/3?file=23936555).

Since you provided a metadata.csv file for the facs data here (https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis?region=us-west-2&prefix=Metadata/), would it also be possible to create a metadata file for the bbknn file?
I already looked at GEO, but this one (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM4505404) seems to just have 
100,000 annotations less than needed for the bbknn file.
So if someone could provide the correct metadata file as *.csv, this would be highly appreciated.

Thanks

**Comment by aopisco** [comment]
@donshiva88 please find it here `s3://czb-tabula-muris-senis/Metadata/tabula-muris-senis-full-metadata.csv`

**Comment by donshiva88** [comment]
> @donshiva88 please find it here `s3://czb-tabula-muris-senis/Metadata/tabula-muris-senis-full-metadata.csv`

Thanks, but the link is not working yet. Can you check again?

**Comment by aopisco** [comment]
Can you try logging out/logging back in?

**Comment by donshiva88** [comment]
Working now. Thanks!
