### ISSUE TITLE
mislabeling of marrow clusters?

### ISSUE THREAD

**Issue by swolock** [czbiohub/tabula-muris-senis#4]
Hello, 

Thanks for providing what promises to be a great resource! I primarily study hematopoiesis and was quickly checking out your bone marrow droplet data. I noticed that several of the `cell_ontology_class` labels seem incorrect, at least based on my experience with similar datasets. I suspect the issue is the result of a simple human error in the matching of `cell_ontology_class` labels with cluster IDs rather than outright misclassification, since some class labels have been assigned to quite unrelated clusters (e.g., "granulocytopoietic cell"). 

Below is a figure with cells colored by the labels from the h5ad files/cellxgene (left panel, arrows marking labels that I'm confident are incorrect) and by marker gene expression (right panel). 

![tab_mur_clusts_labeled](https://user-images.githubusercontent.com/15478852/60823069-b5ce8680-a174-11e9-8aac-d43d69b43985.png)

If you prefer to receive feedback through other channels, let me know.

Best, 
Sam

**Comment by aopisco** [comment]
Hi @swolock I'll check with the tissue expert @transcriptomics and get back to you

**Comment by aopisco** [comment]
@swolock thanks again for finding this label swap! The correct object is now in figshare. Can you please let me know if you can access it and if it's now consistent with your markers? I'll wait for your reply before closing the issue

**Comment by aopisco** [comment]
Closing the issue for now, let me know if you find something else

**Comment by genecell** [comment]
> @aopisco Apologies for not getting back to you on this. I quickly checked the new data files, and they look good to me. Thanks!

Hi @swolock, your cmap colors are beautiful, could you please share your cmap configurations with me, thank you!

**Comment by swolock** [comment]
Thanks @genecell! If you're referring to the gene expression plots, you can check out [this function](https://github.com/AllonKleinLab/klunctions/blob/77d2571e5083faed53b3950ffffc9dd07f60a9e5/sam/Analysis/scBasics/helper_functions.py#L1766) for plotting multiple genes from an AnnData object. The color map itself is just matplotlib's "Reds" color map that has been made slightly darker – see [here](https://github.com/AllonKleinLab/klunctions/blob/77d2571e5083faed53b3950ffffc9dd07f60a9e5/sam/Analysis/scBasics/helper_functions.py#L1681).

For the plot of the cell clusters, I think I used "Paired", but I'm not positive.
