### ISSUE TITLE
How can I find the marker genes used to annotate each cell type?

### ISSUE THREAD

**Issue by amsegura** [czbiohub/tabula-muris-senis#41]
Hello, first I wanted to thank you for this amazing job. It is very helpful for the aging research community. 

I am trying to do some analysis using the brain data, but I need to know the exact markers used for each cell type. I have been looking around in the github account and I haven't found the precise genes used (maybe I just missed those lines of code?). 

Also, I tried to access the AWS data just in case there were more code notebooks there, however it asks me all the time to create an account asking for billing data and credit card information (for example this link: [S3 Public Bucket](https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis/Data-to-reproduce-figures/mutation-analysis-objs/?region=us-west-2&tab=overview). Is the first time I use AWS, is that required to access these public datasets?

Thank you in advance for your help and attention.

**Comment by aopisco** [comment]
hi @amsegura here are the marker genes https://drive.google.com/drive/u/0/folders/1JZgFDmdVlw-UN8Gb_lRxSAdCZfhlzdrH

**Comment by amsegura** [comment]
Thank you so much for your fast response!

Here is where I got confused. I found some of these genes that I can see now in the excel sheet you just send me in the supplementary materials of the *Tabula muris* paper. However, in the "Tabula muris senis-brain non myeloyd.h5ad" file available in the [cellxgene](https://cellxgene.cziscience.com/e/66ff82b4-9380-469c-bc4b-cfa08eacd325.cxg/) website, the name for the neurons is **neuron** or **interneuron**. Sometimes these are terms exchangeable for **excitatory** and **inhibitory** respectively. But sometimes some people are more specific. I just wanted to know if that is the case here and the markers for **inhibitory** neurons that I can see in the excel are the same for the **interneuron** I see in the .h5ad file.

Thank you again!

**Comment by aopisco** [comment]
Each tissue was annotated by a separate group and therefore I don't have further information. Brain was processed by the Wyss-Coray lab at Stanford so I'd suggest you direct any specific questions to them.

**Comment by amsegura** [comment]
Perfect, 

Thank you for all your help.
