### ISSUE TITLE
Are the bam files missing for some cells of the FACS data? What are the 'TK' parameters?

### ISSUE THREAD

**Issue by libraryies** [czbiohub/tabula-muris-senis#45]
Hello!

I have downloaded the whole FACS data, but I met a little problem. In the paper, I noticed that there should be 110824 cells sequenced for FACS. When I sorted out all the bam files according to the provided 'tabula-muris-senis-full-metadata.csv' file, I got a total of 106273 bam files and I didn't find those missing bam files in the AWS database. 

Another question is that I found a part of fastq.gz files of these missing cell files. So, I want to generate bam files using these fastq.gz files. I noticed that you used STAR v.2.5.2b with parameters TK. Can you tell me what the 'TK parameters' mean since I didn't find them in the STAR?

Thank you very much!

**Comment by aopisco** [comment]
hi @libraryies the code used is [here](https://github.com/czbiohub/utilities/blob/main/src/mapping/process_smartseq2/main.nf)

unfortunately I won't be able to help further locating the files

**Comment by libraryies** [comment]
OK, thanks for your reply.
