### ISSUE TITLE
Tabula Muris vs Tabula Muris Senis

### ISSUE THREAD

**Issue by davek44** [czbiohub/tabula-muris-senis#48]
Hi, thanks for the wonderful resource! I'm wondering if the s3 bucket s3://czb-tabula-muris-senis/ contains the data from the original publication, too s3://czbiohub-tabula-muris/. Many of the files in czbiohub-tabula-muris/ are labeled "Glacier Deep Archive" and unavailable.

**Comment by aopisco** [comment]
Yes, tabula-muris-senis contains all tabula-muris. I hope this helps!
