### ISSUE TITLE
Cluster labels for droplet data

### ISSUE THREAD

**Issue by jw156605** [czbiohub/tabula-muris-senis#8]
Is there an easy way to get the cluster labels for the droplet data without parsing through all of the individual scanpy files? The AWS bucket contains such a metadata file, but it only contains cells from the FACS protocol. Thanks!

**Comment by aopisco** [comment]
hi @jw156605 the metadata files are available [here](https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis/Data-objects/?region=us-west-2)
