### ISSUE TITLE
Help downloading data from AWS

### ISSUE THREAD

**Issue by sevans625** [czbiohub/tabula-muris-senis#9]
Hi,

I am trying to download FASTQ files for 10x data from AWS S3

What is the best way to do this? On the AWD page it will only let me download each file individually, I cant download the entire directory.

How do I gain access to the files so that I can start aligning things?

**Comment by aopisco** [comment]
@sevans625 the best way is to sync your files using aws cli
checkout this blog post: https://www.viget.com/articles/set-up-aws-cli-and-download-your-s3-files-from-the-command-line/
and let me know if you need further help

**Comment by cmdcolin** [comment]
You may want to update the link in the README s3, it refers to an aws console link which I think is not public

**Comment by aopisco** [comment]
@cmdcolin the data is public but you need to create a free AWS account. Can you let me know if you're having problems downloading the data?

**Comment by aopisco** [comment]
closing the issue as I didn't get further questions, feel free to reopen
